# https://hakin9.org/hackingtool-all-in-one-hacking-tool-for-hackers/

image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - command: |
      sudo pip3 install -r requirement.txt
      sudo ./install.sh
      sudo hackingtool

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 3000
#     onOpen: open-preview
